// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Persistence.Data;

namespace Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210520095645_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Persistence.Models.MachineLearningModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("MachineLearningModels");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MachineLearningModel");
                });

            modelBuilder.Entity("Model.Persistence.Models.SuperResolutionModel", b =>
                {
                    b.HasBaseType("Model.Persistence.Models.MachineLearningModel");

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<byte>("UpscaleFactor");

                    b.HasDiscriminator().HasValue("SuperResolutionModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Super Resolution SRResNET MSE",
                            Path = "MachineLearningModels\\SuperResolution_SRResNet_MSE\\super_resolution_2x.onnx",
                            UpscaleFactor = (byte)2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Super Resolution SRResNET MSE",
                            Path = "MachineLearningModels\\SuperResolution_SRResNet_MSE\\super_resolution_4x.onnx",
                            UpscaleFactor = (byte)4
                        },
                        new
                        {
                            Id = 3,
                            Name = "Super Resolution SRResNET MSE",
                            Path = "MachineLearningModels\\SuperResolution_SRResNet_MSE\\super_resolution_8x.onnx",
                            UpscaleFactor = (byte)8
                        },
                        new
                        {
                            Id = 4,
                            Name = "Super Resolution SRGAN MSE",
                            Path = "MachineLearningModels\\SuperResolution_SRGAN\\super_resolution_2x.onnx",
                            UpscaleFactor = (byte)2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Super Resolution SRGAN MSE",
                            Path = "MachineLearningModels\\SuperResolution_SRGAN\\super_resolution_4x.onnx",
                            UpscaleFactor = (byte)4
                        },
                        new
                        {
                            Id = 6,
                            Name = "Super Resolution SRGAN MSE",
                            Path = "MachineLearningModels\\SuperResolution_SRGAN\\super_resolution_8x.onnx",
                            UpscaleFactor = (byte)8
                        },
                        new
                        {
                            Id = 7,
                            Name = "Super Resolution SRResNET SSIM",
                            Path = "MachineLearningModels\\SuperResolution_SRResNet_SSIM\\super_resolution_2x.onnx",
                            UpscaleFactor = (byte)2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Super Resolution SRResNET SSIM",
                            Path = "MachineLearningModels\\SuperResolution_SRResNet_SSIM\\super_resolution_4x.onnx",
                            UpscaleFactor = (byte)4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
